GET http://localhost:3001/api/notes/2454

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS code rest client is a pretty handy tool",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/64e7ec4196fe04dcf15334be
