GET http://localhost:3001/api/notes/2454

###
GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/64e7ec4196fe04dcf15334be

###
PUT http://localhost:3001/api/notes/64d52ec79bc9f68ea07748ba
Content-Type: application/json

{
    "content": "Micho Bonito",
    "important": true
}
