DELETE http://localhost:3001/api/people/64e8b8748a071b93edc7313f3154

###
POST http://localhost:3001/api/people
Content-Type : application/json

{
    "name": "Dan Quinn",
    "number": "123456687"
}

###
GET http://localhost:3001/api/people/safsdafl

###
GET http://localhost:3001/api/people/