DELETE http://localhost:3000/api/persons/:id

###
POST http://localhost:3001/api/people
Content-Type : application/json

{
    "name": "Dan Quinn",
    "number": "123456687"
}

###
GET http://localhost:3001/api/people

###
GET http://localhost:3001/api/people/64e7e09cf1c76162a03c843f