DELETE http://localhost:3000/api/persons/:id

###
POST http://localhost:3000/api/persons
Content-Type : application/json

{
    "name": "Dan Quinn",
    "number": "123456687"
}

###
GET http://localhost:3001/api/people
